// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_color_screen_init(void)
{
ui_color = lv_obj_create(NULL);
lv_obj_clear_flag( ui_color, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_color, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_color, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_btnTabPower2 = lv_btn_create(ui_color);
lv_obj_set_width( ui_btnTabPower2, 111);
lv_obj_set_height( ui_btnTabPower2, 60);
lv_obj_set_x( ui_btnTabPower2, -56 );
lv_obj_set_y( ui_btnTabPower2, 210 );
lv_obj_set_align( ui_btnTabPower2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_btnTabPower2, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_btnTabPower2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_btnTabPower2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_btnTabPower2, lv_color_hex(0x050505), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_btnTabPower2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_btnTabPower2, &ui_img_ico_power_png, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_img_opa(ui_btnTabPower2, 50, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_btnTabPower2, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_btnTabPower2, 255, LV_PART_MAIN| LV_STATE_PRESSED);

ui_btnTabColor2 = lv_btn_create(ui_color);
lv_obj_set_width( ui_btnTabColor2, 111);
lv_obj_set_height( ui_btnTabColor2, 60);
lv_obj_set_x( ui_btnTabColor2, 55 );
lv_obj_set_y( ui_btnTabColor2, 210 );
lv_obj_set_align( ui_btnTabColor2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_btnTabColor2, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_btnTabColor2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_btnTabColor2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_btnTabColor2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_btnTabColor2, 50, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_btnTabColor2, &ui_img_ico_color_png, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_color(ui_btnTabColor2, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_btnTabColor2, 255, LV_PART_MAIN| LV_STATE_PRESSED);

ui_Image3 = lv_img_create(ui_color);
lv_img_set_src(ui_Image3, &ui_img_logo_png);
lv_obj_set_width( ui_Image3, LV_SIZE_CONTENT);  /// 202
lv_obj_set_height( ui_Image3, LV_SIZE_CONTENT);   /// 100
lv_obj_set_x( ui_Image3, 0 );
lv_obj_set_y( ui_Image3, -180 );
lv_obj_set_align( ui_Image3, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image3, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image2 = lv_img_create(ui_color);
lv_img_set_src(ui_Image2, &ui_img_bg_color_png);
lv_obj_set_width( ui_Image2, LV_SIZE_CONTENT);  /// 202
lv_obj_set_height( ui_Image2, LV_SIZE_CONTENT);   /// 290
lv_obj_set_x( ui_Image2, 0 );
lv_obj_set_y( ui_Image2, 25 );
lv_obj_set_align( ui_Image2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image2, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_sliderColor = lv_slider_create(ui_color);
lv_slider_set_range(ui_sliderColor, 0,360);
lv_obj_set_width( ui_sliderColor, 8);
lv_obj_set_height( ui_sliderColor, 238);
lv_obj_set_x( ui_sliderColor, -55 );
lv_obj_set_y( ui_sliderColor, 25 );
lv_obj_set_align( ui_sliderColor, LV_ALIGN_CENTER );
lv_obj_set_style_bg_color(ui_sliderColor, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_sliderColor, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_sliderColor, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_sliderColor, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_sliderColor, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_sliderColor, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_sliderColor, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_sliderColor, 255, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_outline_width(ui_sliderColor, 3, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_outline_pad(ui_sliderColor, -3, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_sliderColor, 0, LV_PART_KNOB| LV_STATE_PRESSED);
lv_obj_set_style_pad_right(ui_sliderColor, 0, LV_PART_KNOB| LV_STATE_PRESSED);
lv_obj_set_style_pad_top(ui_sliderColor, 0, LV_PART_KNOB| LV_STATE_PRESSED);
lv_obj_set_style_pad_bottom(ui_sliderColor, 0, LV_PART_KNOB| LV_STATE_PRESSED);

ui_sliderBrightness = lv_slider_create(ui_color);
lv_slider_set_range(ui_sliderBrightness, 0,255);
lv_slider_set_value( ui_sliderBrightness, 128, LV_ANIM_OFF);
if (lv_slider_get_mode(ui_sliderBrightness)==LV_SLIDER_MODE_RANGE ) lv_slider_set_left_value( ui_sliderBrightness, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_sliderBrightness, 8);
lv_obj_set_height( ui_sliderBrightness, 238);
lv_obj_set_x( ui_sliderBrightness, 56 );
lv_obj_set_y( ui_sliderBrightness, 25 );
lv_obj_set_align( ui_sliderBrightness, LV_ALIGN_CENTER );
lv_obj_set_style_bg_color(ui_sliderBrightness, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_sliderBrightness, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_sliderBrightness, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_sliderBrightness, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_sliderBrightness, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_sliderBrightness, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_sliderBrightness, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_sliderBrightness, 255, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_outline_width(ui_sliderBrightness, 3, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_outline_pad(ui_sliderBrightness, -3, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_sliderBrightness, 0, LV_PART_KNOB| LV_STATE_PRESSED);
lv_obj_set_style_pad_right(ui_sliderBrightness, 0, LV_PART_KNOB| LV_STATE_PRESSED);
lv_obj_set_style_pad_top(ui_sliderBrightness, 0, LV_PART_KNOB| LV_STATE_PRESSED);
lv_obj_set_style_pad_bottom(ui_sliderBrightness, 0, LV_PART_KNOB| LV_STATE_PRESSED);

lv_obj_add_event_cb(ui_btnTabPower2, ui_event_btnTabPower2, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_sliderColor, ui_event_sliderColor, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_sliderBrightness, ui_event_sliderBrightness, LV_EVENT_ALL, NULL);

}
