// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_power_screen_init(void)
{
ui_power = lv_obj_create(NULL);
lv_obj_clear_flag( ui_power, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_power, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_power, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_btnTabPower = lv_btn_create(ui_power);
lv_obj_set_width( ui_btnTabPower, 111);
lv_obj_set_height( ui_btnTabPower, 60);
lv_obj_set_x( ui_btnTabPower, -56 );
lv_obj_set_y( ui_btnTabPower, 210 );
lv_obj_set_align( ui_btnTabPower, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_btnTabPower, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_btnTabPower, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_btnTabPower, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_btnTabPower, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_btnTabPower, 50, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_btnTabPower, &ui_img_ico_power_png, LV_PART_MAIN | LV_STATE_DEFAULT );

ui_btnTabColor = lv_btn_create(ui_power);
lv_obj_set_width( ui_btnTabColor, 111);
lv_obj_set_height( ui_btnTabColor, 60);
lv_obj_set_x( ui_btnTabColor, 55 );
lv_obj_set_y( ui_btnTabColor, 210 );
lv_obj_set_align( ui_btnTabColor, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_btnTabColor, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_btnTabColor, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_btnTabColor, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_btnTabColor, lv_color_hex(0x050505), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_btnTabColor, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_btnTabColor, &ui_img_ico_color_png, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_img_opa(ui_btnTabColor, 50, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_btnTabColor, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_btnTabColor, 255, LV_PART_MAIN| LV_STATE_PRESSED);

ui_btnLED = lv_btn_create(ui_power);
lv_obj_set_width( ui_btnLED, 202);
lv_obj_set_height( ui_btnLED, 90);
lv_obj_set_x( ui_btnLED, 0 );
lv_obj_set_y( ui_btnLED, 125 );
lv_obj_set_align( ui_btnLED, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_btnLED, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_btnLED, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_btnLED, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_btnLED, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_btnLED, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_btnLED, &ui_img_btn_pwroff_png, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_color(ui_btnLED, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_btnLED, 0, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_bg_img_src( ui_btnLED, &ui_img_btn_pwron_png, LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_bg_color(ui_btnLED, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_btnLED, 225, LV_PART_MAIN| LV_STATE_PRESSED);

ui_btnLow = lv_btn_create(ui_power);
lv_obj_set_width( ui_btnLow, 202);
lv_obj_set_height( ui_btnLow, 90);
lv_obj_set_x( ui_btnLow, 0 );
lv_obj_set_y( ui_btnLow, 25 );
lv_obj_set_align( ui_btnLow, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_btnLow, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_btnLow, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_btnLow, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_btnLow, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_btnLow, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_btnLow, &ui_img_btn_pwroff_png, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_color(ui_btnLow, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_btnLow, 0, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_bg_img_src( ui_btnLow, &ui_img_btn_pwron_png, LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_bg_color(ui_btnLow, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_btnLow, 225, LV_PART_MAIN| LV_STATE_PRESSED);

ui_btnHigh = lv_btn_create(ui_power);
lv_obj_set_width( ui_btnHigh, 202);
lv_obj_set_height( ui_btnHigh, 90);
lv_obj_set_x( ui_btnHigh, 0 );
lv_obj_set_y( ui_btnHigh, -75 );
lv_obj_set_align( ui_btnHigh, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_btnHigh, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_btnHigh, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_btnHigh, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_btnHigh, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_btnHigh, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_btnHigh, &ui_img_btn_pwroff_png, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_color(ui_btnHigh, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_btnHigh, 0, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_bg_img_src( ui_btnHigh, &ui_img_btn_pwron_png, LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_bg_color(ui_btnHigh, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_btnHigh, 225, LV_PART_MAIN| LV_STATE_PRESSED);

ui_logo = lv_img_create(ui_power);
lv_img_set_src(ui_logo, &ui_img_logo_png);
lv_obj_set_width( ui_logo, LV_SIZE_CONTENT);  /// 202
lv_obj_set_height( ui_logo, LV_SIZE_CONTENT);   /// 100
lv_obj_set_x( ui_logo, 0 );
lv_obj_set_y( ui_logo, -180 );
lv_obj_set_align( ui_logo, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_logo, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_logo, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_icoHight = lv_img_create(ui_power);
lv_img_set_src(ui_icoHight, &ui_img_ico_high_png);
lv_obj_set_width( ui_icoHight, LV_SIZE_CONTENT);  /// 202
lv_obj_set_height( ui_icoHight, LV_SIZE_CONTENT);   /// 90
lv_obj_set_x( ui_icoHight, 0 );
lv_obj_set_y( ui_icoHight, -75 );
lv_obj_set_align( ui_icoHight, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_icoHight, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_icoHight, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_icoLow = lv_img_create(ui_power);
lv_img_set_src(ui_icoLow, &ui_img_ico_low_png);
lv_obj_set_width( ui_icoLow, LV_SIZE_CONTENT);  /// 202
lv_obj_set_height( ui_icoLow, LV_SIZE_CONTENT);   /// 90
lv_obj_set_x( ui_icoLow, 0 );
lv_obj_set_y( ui_icoLow, 25 );
lv_obj_set_align( ui_icoLow, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_icoLow, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_icoLow, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_icoLED = lv_img_create(ui_power);
lv_img_set_src(ui_icoLED, &ui_img_ico_led_png);
lv_obj_set_width( ui_icoLED, LV_SIZE_CONTENT);  /// 202
lv_obj_set_height( ui_icoLED, LV_SIZE_CONTENT);   /// 90
lv_obj_set_x( ui_icoLED, 0 );
lv_obj_set_y( ui_icoLED, 125 );
lv_obj_set_align( ui_icoLED, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_icoLED, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_icoLED, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

lv_obj_add_event_cb(ui_btnTabColor, ui_event_btnTabColor, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_btnLED, ui_event_btnLED, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_btnLow, ui_event_btnLow, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_btnHigh, ui_event_btnHigh, LV_EVENT_ALL, NULL);

}
