// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_power
void ui_power_screen_init(void);
lv_obj_t *ui_power;
lv_obj_t *ui_btnTabPower;
void ui_event_btnTabColor( lv_event_t * e);
lv_obj_t *ui_btnTabColor;
void ui_event_btnLED( lv_event_t * e);
lv_obj_t *ui_btnLED;
void ui_event_btnLow( lv_event_t * e);
lv_obj_t *ui_btnLow;
void ui_event_btnHigh( lv_event_t * e);
lv_obj_t *ui_btnHigh;
lv_obj_t *ui_logo;
lv_obj_t *ui_icoHight;
lv_obj_t *ui_icoLow;
lv_obj_t *ui_icoLED;


// SCREEN: ui_color
void ui_color_screen_init(void);
lv_obj_t *ui_color;
void ui_event_btnTabPower2( lv_event_t * e);
lv_obj_t *ui_btnTabPower2;
lv_obj_t *ui_btnTabColor2;
lv_obj_t *ui_Image3;
lv_obj_t *ui_Image2;
void ui_event_sliderColor( lv_event_t * e);
lv_obj_t *ui_sliderColor;
void ui_event_sliderBrightness( lv_event_t * e);
lv_obj_t *ui_sliderBrightness;
lv_obj_t *ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_btnTabColor( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_RELEASED) {
      _ui_screen_change( &ui_color, LV_SCR_LOAD_ANIM_FADE_ON, 25, 0, &ui_color_screen_init);
}
}
void ui_event_btnLED( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_RELEASED) {
      ledStripes( e );
}
}
void ui_event_btnLow( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_RELEASED) {
      lowBeam( e );
}
}
void ui_event_btnHigh( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_RELEASED) {
      highBeam( e );
}
}
void ui_event_btnTabPower2( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_RELEASED) {
      _ui_screen_change( &ui_power, LV_SCR_LOAD_ANIM_FADE_ON, 25, 0, &ui_power_screen_init);
      _ui_screen_delete( &ui_color);
}
}
void ui_event_sliderColor( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_VALUE_CHANGED) {
      color_value( e );
}
}
void ui_event_sliderBrightness( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_VALUE_CHANGED) {
      brightness_value( e );
}
}

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), true, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_power_screen_init();
ui_color_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_power);
}
