// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_power
void ui_power_screen_init(void);
extern lv_obj_t *ui_power;
extern lv_obj_t *ui_btnTabPower;
void ui_event_btnTabColor( lv_event_t * e);
extern lv_obj_t *ui_btnTabColor;
void ui_event_btnLED( lv_event_t * e);
extern lv_obj_t *ui_btnLED;
void ui_event_btnLow( lv_event_t * e);
extern lv_obj_t *ui_btnLow;
void ui_event_btnHigh( lv_event_t * e);
extern lv_obj_t *ui_btnHigh;
extern lv_obj_t *ui_logo;
extern lv_obj_t *ui_icoHight;
extern lv_obj_t *ui_icoLow;
extern lv_obj_t *ui_icoLED;
// SCREEN: ui_color
void ui_color_screen_init(void);
extern lv_obj_t *ui_color;
void ui_event_btnTabPower2( lv_event_t * e);
extern lv_obj_t *ui_btnTabPower2;
extern lv_obj_t *ui_btnTabColor2;
extern lv_obj_t *ui_Image3;
extern lv_obj_t *ui_Image2;
void ui_event_sliderColor( lv_event_t * e);
extern lv_obj_t *ui_sliderColor;
void ui_event_sliderBrightness( lv_event_t * e);
extern lv_obj_t *ui_sliderBrightness;
extern lv_obj_t *ui____initial_actions0;

LV_IMG_DECLARE( ui_img_ico_power_png);   // assets/ico_power.png
LV_IMG_DECLARE( ui_img_ico_color_png);   // assets/ico_color.png
LV_IMG_DECLARE( ui_img_btn_pwroff_png);   // assets/btn_pwrOff.png
LV_IMG_DECLARE( ui_img_btn_pwron_png);   // assets/btn_pwrOn.png
LV_IMG_DECLARE( ui_img_logo_png);   // assets/logo.png
LV_IMG_DECLARE( ui_img_ico_high_png);   // assets/ico_high.png
LV_IMG_DECLARE( ui_img_ico_low_png);   // assets/ico_low.png
LV_IMG_DECLARE( ui_img_ico_led_png);   // assets/ico_led.png
LV_IMG_DECLARE( ui_img_bg_color_png);   // assets/bg_color.png



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
