// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void ledStripes(lv_event_t * e);
void lowBeam(lv_event_t * e);
void highBeam(lv_event_t * e);
void color_value(lv_event_t * e);
void brightness_value(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
