// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"
#include "main.h"

void brightness_value(lv_event_t * e)
{
	lv_obj_t * slider = lv_event_get_target (e);
	int32_t v = lv_slider_get_value(slider);
	brightness(v);
}

void color_value(lv_event_t * e)
{
	lv_obj_t * slider = lv_event_get_target (e);
	int32_t v = lv_slider_get_value(slider);
	color(v);
}

void highBeam(lv_event_t * e)
{
	toggleRelay4();
}

void lowBeam(lv_event_t * e)
{
	toggleRelay3();
}

void ledStripes(lv_event_t * e)
{
	toggleRelay1();
	toggleRelay2();
}